---

- name: "Create VM folder - {{ vmware_folder_parent }}{{ '/' if vmware_folder_parent | default('') != '' }}{{ vmware_folder_name }}"
  community.vmware.vcenter_folder:
    hostname: "{{ vmware_vcenter_hostname }}"
    username: "{{ vmware_vcenter_username }}"
    password: "{{ vmware_vcenter_password }}"
    validate_certs: false
    datacenter: "{{ vmware_datacenter }}"
    folder_name: "{{ vmware_folder_name }}"
    parent_folder: "{{ vmware_folder_parent }}"

- set_fact:
    vmware_folder_parent: "{{ vmware_folder_parent }}{{ '/' if vmware_folder_parent | default('') != '' }}{{ vmware_folder_name }}"
